import type { Credential } from './types';

/**
 * The verified credential set: 9 Google + 2 Udemy.
 *
 * Note it is NOT '11 Google certifications' — that claim was wrong and was
 * removed in Phase 1. Every URL here was checked on 2026-09-18, including the
 * Cybersecurity entry, which previously pointed at a Data Analytics credential.
 *
 * `featured: true` marks the professional certificates, for surfaces that show
 * a subset. /certifications renders all of them.
 */
export const credentials: Credential[] = [
  {
    id: 'cred-google-cybersecurity-professional',
    title: 'Google Cybersecurity Professional',
    issuer: 'Google',
    issuedAt: 'Nov 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/MDMFD7XJJXL4',
    category: 'Security',
    description: 'Eight-course specialization: network security, Linux, Python, SQL and SIEM tooling.',
    featured: true,
    color: '#ef4444',
    icon: '🔒',
  },
  {
    id: 'cred-google-data-analytics-professional',
    title: 'Google Data Analytics Professional',
    issuer: 'Google',
    issuedAt: '2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/W0BZT6HTJXZE',
    category: 'Data',
    description: 'Eight-course specialization: data cleaning, analysis, R, SQL and Tableau.',
    featured: true,
    color: '#f59e0b',
    icon: '📊',
  },
  {
    id: 'cred-google-ai-essentials',
    title: 'Google AI Essentials',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/0YL581G13RX6',
    category: 'AI',
    description: 'Generative AI fundamentals, responsible AI practice and practical tool use.',
    featured: true,
    color: '#986ef7',
    icon: '🤖',
  },
  {
    id: 'cred-python-bootcamp-master-python-with-real-world-pr',
    title: 'Python Bootcamp: Master Python with Real-World Projects',
    issuer: 'Udemy',
    issuedAt: 'Jun 2025',
    credentialUrl: 'https://www.udemy.com/certificate/UC-ea3dcd47-fe5c-4073-b11b-15d417c0f56a/',
    category: 'Languages',
    description: 'Python programming from fundamentals through applied projects.',
    featured: true,
    color: '#3b82f6',
    icon: '🐍',
  },
  {
    id: 'cred-discover-the-art-of-prompting',
    title: 'Discover the Art of Prompting',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/TUEGAHF57ZTM',
    category: 'AI',
    description: 'Prompt design techniques for generative models.',
    featured: false,
    color: '#10b981',
    icon: '💬',
  },
  {
    id: 'cred-introduction-to-ai',
    title: 'Introduction to AI',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/2D6R17WJ0GV4',
    category: 'AI',
    description: 'Foundations of artificial intelligence, machine learning and neural networks.',
    featured: false,
    color: '#14b8a6',
    icon: '🧠',
  },
  {
    id: 'cred-maximize-productivity-with-ai-tools',
    title: 'Maximize Productivity With AI Tools',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/IFKTQQ411CQZ',
    category: 'AI',
    description: 'Applying generative AI tools to everyday working practice.',
    featured: false,
    color: '#f97316',
    icon: '⚡',
  },
  {
    id: 'cred-use-ai-responsibly',
    title: 'Use AI Responsibly',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/CVLTNGKIT1XW',
    category: 'AI',
    description: 'Bias, fairness and responsible deployment of AI systems.',
    featured: false,
    color: '#af63f8',
    icon: '🛡️',
  },
  {
    id: 'cred-foundations-of-cybersecurity',
    title: 'Foundations of Cybersecurity',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/50E0LB750MEX',
    category: 'Security',
    description: 'Security domains, threat landscape and core defensive concepts.',
    featured: false,
    color: '#ef4444',
    icon: '🔐',
  },
  {
    id: 'cred-play-it-safe-manage-security-risks',
    title: 'Play It Safe: Manage Security Risks',
    issuer: 'Google',
    issuedAt: 'Aug 2025',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/2GA0972VLLSD',
    category: 'Security',
    description: 'Risk management frameworks, security audits and controls.',
    featured: false,
    color: '#f43f5e',
    icon: '🛡️',
  },
  {
    id: 'cred-html-fundamentals',
    title: 'HTML Fundamentals',
    issuer: 'Udemy',
    issuedAt: 'Jun 2021',
    credentialUrl: 'https://www.udemy.com/certificate/UC-4c91f9fa-2aee-4eaf-8274-806cce39ca59/',
    category: 'Web',
    description: 'Introductory HTML and document structure.',
    featured: false,
    color: '#94a3b8',
    icon: '🌐',
  },
];
