import type { OpenSourceContribution } from './types';

/**
 * Upstream contributions.
 *
 * Every entry was re-verified against the GitHub API on 2026-09-20 — state,
 * merge flag, merge date, open date, author, title and diff size all read from
 * `/repos/{owner}/{repo}/pulls/{n}` and its `files` collection. This file is the
 * cached result, so the public site never depends on GitHub being reachable at
 * render time and never renders a status that has not been checked.
 *
 * `problem`, `change` and `verification` are written from each pull request's
 * own description. Nothing is inferred: where a request documents no tests, the
 * field is absent and the page says so rather than implying evidence that the
 * request does not carry.
 *
 * `loop-engineering` is `cobusgreyling/loop-engineering`. It is not
 * `block/goose` — goose#395 and goose#437 are unrelated PRs by another author.
 */
export const openSourceContributions: OpenSourceContribution[] = [
  {
    id: 'oss-pydantic-ai-5969',
    repository: 'pydantic/pydantic-ai',
    organization: 'pydantic',
    prNumber: 5969,
    url: 'https://github.com/pydantic/pydantic-ai/pull/5969',
    title: 'Fix AGUIAdapter.dump_messages reordering ToolReturnPart after UserPromptPart',
    summary:
      'Message parts were being re-ordered during adapter serialization, putting a tool return after the user prompt that triggered it.',
    problem:
      'A ModelRequest carrying both a ToolReturnPart and a UserPromptPart came out of AG-UI dumping in the wrong order — the user message first, the tool message after it. Providers that require a tool result to follow its tool call immediately, Anthropic and Bedrock among them, then rejected the replayed history.',
    change:
      'Preserved the original ModelRequest.parts ordering through dumping, with a _flush_user_content() helper that flushes buffered user content at ordering boundaries rather than at the end, and added regression coverage for the ToolReturnPart-then-UserPromptPart case.',
    verification: [
      'Regression test test_dump_messages_preserves_part_order added to tests/test_ag_ui.py and run under pytest.',
      'ruff check run over the changed adapter and test file.',
    ],
    issueRef: '#5964',
    status: 'merged',
    openedAt: '2026-06-17',
    mergedAt: '2026-07-01',
    languages: ['Python'],
    areas: ['AI', 'Agents'],
    diff: {
      files: 2,
      additions: 91,
      deletions: 8,
      paths: [
        { path: 'pydantic_ai_slim/pydantic_ai/ui/ag_ui/_adapter.py', additions: 22, deletions: 8 },
        { path: 'tests/test_ag_ui.py', additions: 69, deletions: 0 },
      ],
    },
    proof: [
      {
        id: 'oss-pydantic-ai-5969-merged',
        type: 'merged-pr',
        label: 'Merged upstream',
        sourceUrl: 'https://github.com/pydantic/pydantic-ai/pull/5969',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
  {
    id: 'oss-promptfoo-9781',
    repository: 'promptfoo/promptfoo',
    organization: 'promptfoo',
    prNumber: 9781,
    url: 'https://github.com/promptfoo/promptfoo/pull/9781',
    title: 'Add per-test repeat option',
    summary:
      'Allows an individual test case to be repeated, so flaky or non-deterministic model behaviour can be measured per test rather than per run.',
    problem:
      'Repeat count could only be set globally. Measuring how non-deterministic one test case was therefore meant repeating the entire evaluation, paying for every other test to run again as well.',
    change:
      'Added tests[].options.repeat, which overrides the global repeat for that test only. Each repeat index gets its own cache namespace — including index 0 — so repeated runs neither reuse nor overwrite the ordinary non-repeat cache entry. Scenario config now inherits all options fields, matching the existing vars/metadata/assert inheritance, with scenario test options still taking precedence. Invalid values fall back to the effective global repeat and are diagnosed by the public Zod schema and the generated JSON schema.',
    verification: [
      '467 tests passed across six evaluator, type and config-schema suites under vitest.',
      'Generated JSON schema regenerated byte-for-byte clean; typecheck, lint, format and the repository architecture check all passed.',
      'Production documentation site build passed.',
      'Exercised end to end through the local CLI, covering scenario precedence and a fractional repeat value falling back to a single run.',
    ],
    status: 'merged',
    openedAt: '2026-06-16',
    mergedAt: '2026-06-21',
    languages: ['TypeScript'],
    areas: ['AI', 'Evaluation', 'Developer Tools'],
    diff: {
      files: 10,
      additions: 208,
      deletions: 16,
      paths: [
        { path: 'src/evaluator.ts', additions: 28, deletions: 10 },
        { path: 'src/types/index.ts', additions: 3, deletions: 0 },
        { path: 'site/docs/configuration/test-cases.md', additions: 17, deletions: 0 },
        { path: 'site/static/config-schema.json', additions: 5, deletions: 0 },
        { path: 'test/evaluator/basic.test.ts', additions: 56, deletions: 0 },
        { path: 'test/evaluator/scenarios.test.ts', additions: 56, deletions: 0 },
        { path: 'test/config-schema.test.ts', additions: 18, deletions: 0 },
        { path: 'test/types/index.test.ts', additions: 12, deletions: 0 },
        { path: 'test/evaluator/repeatCache.test.ts', additions: 11, deletions: 4 },
        { path: 'test/evaluator/runEval.test.ts', additions: 2, deletions: 2 },
      ],
    },
    proof: [
      {
        id: 'oss-promptfoo-9781-merged',
        type: 'merged-pr',
        label: 'Merged upstream',
        sourceUrl: 'https://github.com/promptfoo/promptfoo/pull/9781',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
  {
    id: 'oss-loop-engineering-395',
    repository: 'cobusgreyling/loop-engineering',
    organization: 'cobusgreyling',
    prNumber: 395,
    url: 'https://github.com/cobusgreyling/loop-engineering/pull/395',
    title: 'Harden loop-action command execution against unquoted shell expansion',
    summary:
      'Command execution passed unquoted values to the shell, so paths or arguments containing shell metacharacters could change the command being run.',
    problem:
      'The action spliced inputs.command into its run: script as raw text, before bash ever parsed it. For a multi-line command: | block that silently broke sandbox isolation — only the first line reached loop-sandbox run --, and every later line executed as a bare top-level statement on the runner, outside both the sandbox and the circuit breaker.',
    change:
      'Wrote the command to a temporary script passed through env:, so the workflow YAML never re-templates it, and invoked it as a single quoted bash "$SCRIPT" call on both the sandboxed and the direct path. The README gained safe-usage documentation and an explicit warning against embedding untrusted input in command.',
    status: 'merged',
    openedAt: '2026-07-25',
    mergedAt: '2026-07-27',
    languages: ['YAML', 'Shell'],
    areas: ['Security', 'Developer Tools'],
    diff: {
      files: 2,
      additions: 67,
      deletions: 6,
      paths: [
        { path: 'tools/loop-action/action.yml', additions: 19, deletions: 4 },
        { path: 'tools/loop-action/README.md', additions: 48, deletions: 2 },
      ],
    },
    proof: [
      {
        id: 'oss-loop-engineering-395-merged',
        type: 'merged-pr',
        label: 'Merged upstream',
        sourceUrl: 'https://github.com/cobusgreyling/loop-engineering/pull/395',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
  {
    id: 'oss-loop-engineering-437',
    repository: 'cobusgreyling/loop-engineering',
    organization: 'cobusgreyling',
    prNumber: 437,
    url: 'https://github.com/cobusgreyling/loop-engineering/pull/437',
    title: 'loop_estimate_cost honors early_exit_required',
    summary:
      'Cost estimation ignored the early-exit flag, so estimates did not match what the loop would actually execute.',
    problem:
      "The MCP server's loop_estimate_cost re-implemented the loop-cost realistic-mix table by hand instead of importing it, and the copy never read pattern.cost.early_exit_required. For early-exit patterns that overestimated the realistic cost by roughly three times against the loop-cost library the documentation points users at.",
    change:
      'Added the loop-cost package as a sibling file: dependency — the same pattern mcp-server already uses for loop-audit, loop-gate and loop-context — and called its estimateCost() directly instead of maintaining a second mix table, so the two tools cannot drift apart again.',
    verification: [
      'A regression test added to test/server.test.mjs with an early-exit fixture pattern, checked to fail against the pre-fix code and pass against the fix.',
      'npm test passing for the MCP server (26/26) and for loop-cost (12/12).',
    ],
    issueRef: '#434',
    status: 'merged',
    openedAt: '2026-07-29',
    mergedAt: '2026-07-31',
    languages: ['TypeScript', 'JavaScript'],
    areas: ['AI', 'Developer Tools'],
    diff: {
      files: 5,
      additions: 91,
      deletions: 63,
      paths: [
        { path: 'tools/mcp-server/src/index.ts', additions: 13, deletions: 31 },
        { path: 'tools/mcp-server/dist/index.js', additions: 13, deletions: 30 },
        { path: 'tools/mcp-server/test/server.test.mjs', additions: 40, deletions: 1 },
        { path: 'tools/mcp-server/package.json', additions: 1, deletions: 0 },
        { path: 'tools/mcp-server/package-lock.json', additions: 24, deletions: 1 },
      ],
    },
    proof: [
      {
        id: 'oss-loop-engineering-437-merged',
        type: 'merged-pr',
        label: 'Merged upstream',
        sourceUrl: 'https://github.com/cobusgreyling/loop-engineering/pull/437',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
  {
    id: 'oss-mcts-233',
    repository: 'MCP-Audit/MCTS',
    organization: 'MCP-Audit',
    prNumber: 233,
    url: 'https://github.com/MCP-Audit/MCTS/pull/233',
    title: 'Add doctor optional toolchain checks',
    summary:
      'Extends the doctor command to report on optional toolchain dependencies instead of failing opaquely when they are absent.',
    problem:
      'The doctor command gave no way to tell a missing optional dependency apart from a broken core installation: absent optional tooling failed the check rather than reporting itself, and Rich markup meant the extras being discussed did not even render literally in the output.',
    change:
      'Added deep-mode checks for the optional extras and for the semgrep, pip-audit and opa command-line tools, plus an API-key readiness warning. Missing optional tooling now warns instead of failing a core-only install, and the output labels are escaped so the extras render as written.',
    verification: [
      'Doctor tests added for both the missing and the present optional-toolchain cases; pytest tests/test_doctor.py reported 6 passed.',
    ],
    issueRef: '#212',
    status: 'merged',
    openedAt: '2026-06-11',
    mergedAt: '2026-06-11',
    languages: ['Python'],
    areas: ['Developer Tools'],
    diff: {
      files: 2,
      additions: 99,
      deletions: 1,
      paths: [
        { path: 'src/mcts/cli/doctor.py', additions: 43, deletions: 1 },
        { path: 'tests/test_doctor.py', additions: 56, deletions: 0 },
      ],
    },
    proof: [
      {
        id: 'oss-mcts-233-merged',
        type: 'merged-pr',
        label: 'Merged upstream',
        sourceUrl: 'https://github.com/MCP-Audit/MCTS/pull/233',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
  {
    id: 'oss-asf-dna-195',
    repository: 'AcademySoftwareFoundation/dna',
    organization: 'AcademySoftwareFoundation',
    prNumber: 195,
    url: 'https://github.com/AcademySoftwareFoundation/dna/pull/195',
    title: 'Fix SPI v2 Uvicorn app target',
    summary:
      'Documentation pointed at the wrong ASGI application target, so following it verbatim failed to start the service.',
    problem:
      'The documented startup command for the SPI v2 backend named the wrong ASGI target, so a reader following the README exactly could not start the service.',
    change:
      'Corrected the Uvicorn target in the service README to the FastAPI application object. A one-line change, and the smallest contribution here — but a wrong getting-started command is the first thing a new contributor hits.',
    verification: [
      'Documentation-only change; the corrected command was checked to name the application object.',
    ],
    issueRef: '#34',
    status: 'merged',
    openedAt: '2026-09-15',
    mergedAt: '2026-09-17',
    languages: ['Markdown'],
    areas: ['Documentation', 'Infrastructure'],
    diff: {
      files: 1,
      additions: 1,
      deletions: 1,
      paths: [
        { path: 'experimental/spi/note_assistant_v2/README.md', additions: 1, deletions: 1 },
      ],
    },
    proof: [
      {
        id: 'oss-asf-dna-195-merged',
        type: 'merged-pr',
        label: 'Merged upstream',
        sourceUrl: 'https://github.com/AcademySoftwareFoundation/dna/pull/195',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
  {
    id: 'oss-eye-tracker-61',
    repository: 'shaal/eye-tracker',
    organization: 'shaal',
    prNumber: 61,
    url: 'https://github.com/shaal/eye-tracker/pull/61',
    title: 'Tell a collapsed axis apart from a uniform offset in describeBiasPattern',
    summary:
      'Bias description conflated two distinct failure shapes — an axis with no spread and an axis uniformly shifted — reporting both the same way.',
    problem:
      'The diagnostic reported a collapsed vertical channel — predicted y nearly constant while target y swept most of the screen — as a uniform offset, and advised the user to recalibrate. Recalibration cannot repair a collapsed axis. The function checked only direction consistency and magnitude relative to accuracy, and both failure shapes point every bias arrow the same way, so the uniformity test could not separate them.',
    change:
      'Regressed bias against target position independently per axis, which does separate them: a uniform offset gives a slope near zero, a collapsed axis a slope near minus one. The slope check runs before the uniformity check, a collapsed axis is now named as such per axis, and the message points at the eye-zoom and resolvable-step diagnostics instead of recommending recalibration. Existing thresholds were left untouched, and the one new threshold is justified against the two data points actually available.',
    verification: [
      'Four tests added to the diagnostics bundle suite: the recorded session classified as a collapsed axis rather than an offset, the other axis reported independently, a mirrored fixture proving the detection is not hardcoded to one axis, and the existing uniform-offset fixture re-asserted as still an offset.',
      'Core suite 75/75 and native suite 173/173 passing; the core workspace typecheck clean.',
    ],
    issueRef: '#58',
    // Open, not merged. Re-checked against the API on 2026-09-20: state "open",
    // merged false, merged_at null.
    status: 'open',
    openedAt: '2026-07-26',
    languages: ['TypeScript'],
    areas: ['Data Analysis'],
    diff: {
      files: 2,
      additions: 208,
      deletions: 0,
      paths: [
        { path: 'packages/core/src/diagnostics/bundle.ts', additions: 64, deletions: 0 },
        { path: 'packages/core/src/diagnostics/bundle.test.ts', additions: 144, deletions: 0 },
      ],
    },
    proof: [
      {
        id: 'oss-eye-tracker-61-open',
        // Deliberately not `merged-pr`: this request is open, and the merged
        // badge would claim an outcome that has not happened.
        type: 'pull-request',
        label: 'Open upstream pull request',
        sourceUrl: 'https://github.com/shaal/eye-tracker/pull/61',
        verified: true,
        asOf: '2026-09-20',
      },
    ],
  },
];
