import type { Skill } from './types';

/**
 * Canonical technology registry.
 *
 * No proficiency scores — Phase 1 removed those because they were self-assigned
 * and measured nothing. A skill earns its place by pointing at the projects,
 * contributions and research it was actually used in, and validation fails if
 * any of those references do not resolve.
 *
 * `shortName` exists for constrained surfaces (the physics pills, chips).
 */
export const skills: Skill[] = [
  // ───────────────────────────── Languages ─────────────────────────────
  {
    slug: 'python',
    name: 'Python',
    category: 'Languages',
    color: '#3b82f6',
    projectSlugs: ['cortexward', 'knowledgeguard', 'meditalk'],
    contributionIds: ['oss-pydantic-ai-5969', 'oss-mcts-233', 'oss-asf-dna-195'],
    researchSlugs: ['knowledgeguard', 'cortexward-verification'],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'typescript',
    name: 'TypeScript',
    category: 'Languages',
    color: '#6366f1',
    projectSlugs: ['veripatch', 'cs-learning-game', 'todo-tracker-pro', 'zakatlink'],
    contributionIds: ['oss-promptfoo-9781', 'oss-eye-tracker-61'],
    researchSlugs: [],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'javascript',
    name: 'JavaScript',
    category: 'Languages',
    color: '#f59e0b',
    projectSlugs: ['sceneforge', 'buildsphere', 'smart-notebook', 'eduresource-hub'],
    contributionIds: ['oss-loop-engineering-395', 'oss-loop-engineering-437'],
    researchSlugs: [],
    featured: true,
    sortOrder: 3,
  },
  {
    slug: 'dart',
    name: 'Dart',
    category: 'Languages',
    color: '#06b6d4',
    projectSlugs: ['emergency-mesh', 'rodift'],
    contributionIds: [],
    researchSlugs: ['emergency-mesh-protocol'],
    featured: true,
    sortOrder: 4,
  },
  {
    slug: 'sql',
    name: 'SQL',
    category: 'Languages',
    color: '#10b981',
    projectSlugs: ['rodift', 'zakatlink'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 5,
  },
  {
    slug: 'kotlin',
    name: 'Kotlin',
    category: 'Languages',
    color: '#a855f7',
    shortName: 'Kotlin',
    projectSlugs: ['emergency-mesh'],
    contributionIds: [],
    researchSlugs: ['emergency-mesh-protocol'],
    featured: true,
    sortOrder: 6,
  },
  {
    slug: 'html-css',
    name: 'HTML / CSS',
    category: 'Languages',
    color: '#f97316',
    shortName: 'CSS',
    projectSlugs: ['eduresource-hub'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 7,
  },

  // ───────────────────────────── Frontend ─────────────────────────────
  {
    slug: 'nextjs',
    name: 'Next.js',
    category: 'Frontend',
    color: '#14b8a6',
    projectSlugs: ['rodift', 'cs-learning-game', 'buildsphere', 'smart-notebook'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'react',
    name: 'React',
    category: 'Frontend',
    color: '#38bdf8',
    projectSlugs: ['sceneforge', 'zakatlink'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'webgl',
    name: 'WebGL',
    category: 'Frontend',
    color: '#8b5cf6',
    projectSlugs: ['buildsphere'],
    contributionIds: [],
    researchSlugs: [],
    featured: false,
  },

  // ───────────────────────────── Backend ─────────────────────────────
  {
    slug: 'nodejs',
    name: 'Node.js',
    category: 'Backend',
    color: '#22c55e',
    projectSlugs: ['veripatch', 'sceneforge', 'zakatlink'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    category: 'Backend',
    color: '#22c55e',
    projectSlugs: ['rodift'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    category: 'Backend',
    color: '#38bdf8',
    shortName: 'Postgres',
    projectSlugs: ['rodift', 'zakatlink'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 3,
  },
  {
    slug: 'postgis',
    name: 'PostGIS',
    category: 'Backend',
    color: '#14b8a6',
    projectSlugs: ['rodift'],
    contributionIds: [],
    researchSlugs: [],
    featured: false,
  },

  // ─────────────────────────────── AI ───────────────────────────────
  {
    slug: 'rag',
    name: 'RAG',
    category: 'AI',
    color: '#d946ef',
    projectSlugs: ['knowledgeguard'],
    contributionIds: [],
    researchSlugs: ['knowledgeguard'],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'llm-agents',
    name: 'LLM Agents',
    category: 'AI',
    color: '#a855f7',
    shortName: 'Agents',
    projectSlugs: ['cortexward'],
    contributionIds: ['oss-pydantic-ai-5969'],
    researchSlugs: ['cortexward-verification'],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'evaluation',
    name: 'Evaluation',
    category: 'AI',
    color: '#8b5cf6',
    projectSlugs: ['knowledgeguard'],
    contributionIds: ['oss-promptfoo-9781'],
    researchSlugs: ['knowledgeguard'],
    featured: true,
    sortOrder: 3,
  },

  // ───────────────────────────── Security ─────────────────────────────
  {
    slug: 'static-analysis',
    name: 'Static Analysis',
    category: 'Security',
    color: '#ef4444',
    shortName: 'Static Analysis',
    projectSlugs: ['cortexward'],
    contributionIds: [],
    researchSlugs: ['cortexward-verification'],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'cryptography',
    name: 'Cryptography',
    category: 'Security',
    color: '#f43f5e',
    shortName: 'Crypto',
    projectSlugs: ['emergency-mesh'],
    contributionIds: [],
    researchSlugs: ['emergency-mesh-protocol'],
    featured: true,
    sortOrder: 2,
  },

  // ───────────────────────────── Mobile ─────────────────────────────
  {
    slug: 'flutter',
    name: 'Flutter',
    category: 'Mobile',
    color: '#38bdf8',
    projectSlugs: ['rodift', 'emergency-mesh'],
    contributionIds: [],
    researchSlugs: ['emergency-mesh-protocol'],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'ble',
    name: 'BLE',
    category: 'Mobile',
    color: '#06b6d4',
    projectSlugs: ['emergency-mesh'],
    contributionIds: [],
    researchSlugs: ['emergency-mesh-protocol'],
    featured: true,
    sortOrder: 2,
  },

  // ───────────────────────────── Systems ─────────────────────────────
  {
    slug: 'ffmpeg',
    name: 'FFmpeg',
    category: 'Systems',
    color: '#f59e0b',
    projectSlugs: ['sceneforge'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'headless-chrome',
    name: 'Headless Chrome',
    category: 'Systems',
    color: '#84cc16',
    shortName: 'Headless',
    projectSlugs: ['sceneforge'],
    contributionIds: [],
    researchSlugs: [],
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'linux',
    name: 'Linux',
    category: 'Systems',
    color: '#94a3b8',
    projectSlugs: [],
    contributionIds: [],
    researchSlugs: [],
    featured: false,
  },

  // ─────────────────────── Infrastructure / Tools ───────────────────────
  {
    slug: 'docker',
    name: 'Docker',
    category: 'Infrastructure',
    color: '#0ea5e9',
    projectSlugs: ['veripatch', 'cortexward'],
    contributionIds: [],
    researchSlugs: ['cortexward-verification'],
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'cli',
    name: 'CLI Design',
    category: 'Developer Tools',
    color: '#f97316',
    shortName: 'CLI',
    projectSlugs: ['veripatch'],
    contributionIds: ['oss-mcts-233'],
    researchSlugs: [],
    featured: true,
    sortOrder: 1,
  },
];
