/**
 * CODEX INFINITUM — Living Realm Engine Registry (Phase 10.6)
 * Contains the interactive, curriculum-based specifications for all CS worlds,
 * including landmarks, progressive descriptions, simulation paths, and cross-realm links.
 */

import type { RealmKnowledgeDefinition } from "./types";

const SILICON_FOUNDRY_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "silicon-foundry",
  title: "Signal Path — Electricity to Result",
  welcomeSpeech: "We are no longer looking at the machine. We are inside it.",
  cameraOverview: {
    position: [12, 10, 16],
    lookAt: [0, 1, -10],
  },
  landmarks: [
    {
      id: "cpu-tower",
      name: "Processor Tower",
      type: "core",
      position: [0, 0, -10],
      pos2D: { x: 0.45, y: 0.5 },
      whatIsIt: "The CPU Core executing digital operations.",
      whyMatters: "Software needs a physical body. Every line of code is eventually compiled into binary and executed here as electrical signals.",
      howItWorks: {
        beginner: "The brain of the computer. It takes in instructions one by one, reads what they want, and executes them like a super-fast chef following a recipe.",
        intermediate: "Runs the instruction cycle: FETCH (retrieves 32/64-bit opcode from L1 instruction cache) -> DECODE (translates opcode via control unit logic) -> EXECUTE (runs arithmetic/logic in the ALU).",
        expert: "A multi-stage superscalar out-of-order execution pipeline. Uses branch prediction (speculative execution) and vector units (AVX-512) to maximize instructions per cycle (IPC) at 4.5+ GHz.",
      },
      realUse: "ALU in modern microprocessors (like Intel Core i9 or Apple Silicon M-Series).",
      difficultyLevel: "Expert",
      skillsUnlocked: ["CPU Instruction Pipeline Design", "Assembly Programming"],
      connectedRealms: ["the-kernel", "code-helix"],
      connectedProjects: [
        { name: "VisiRoD FIRS", slug: "visirod-firs" },
        { name: "CommentFellows", slug: "commentfellows" },
      ],
      nexusComment: "Watch how the core pulses. That's the clock speed dictating billions of steps a second.",
    },
    {
      id: "ram-city",
      name: "Memory Array City",
      type: "node",
      position: [7.5, 0, -10],
      pos2D: { x: 0.8, y: 0.5 },
      whatIsIt: "Random Access Memory modules.",
      whyMatters: "Provides fast, volatile, random-access storage for active programs. Without RAM, the CPU would waste 99% of its cycles waiting for disk storage.",
      howItWorks: {
        beginner: "A giant chalkboard where the computer scribbles numbers it's currently using. When the power goes off, the chalkboard is wiped clean.",
        intermediate: "Dynamic RAM organizes bits into addressable capacitor arrays. It periodically refreshes columns to keep charge, communicating with CPU cache over high-speed buses.",
        expert: "Synchronous DRAM utilizing dual-channel architecture. Transfers data on both rising and falling edges of the clock (DDR5) with bandwidths exceeding 60 GB/s and sub-15ns access latency.",
      },
      realUse: "System Main Memory (DDR5 DIMMs, LPDDR5X).",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Virtual Memory Mapping", "Caching Strategy"],
      connectedRealms: ["the-kernel", "data-archives"],
      connectedProjects: [{ name: "Bus Reservation", slug: "bus-reservation" }],
      nexusComment: "Every active process gets its own slice of this memory grid. The Kernel enforces strict boundaries so they don't overwrite each other.",
    },
    {
      id: "logic-factory",
      name: "Logic Gate Factory",
      type: "factory",
      position: [-7.5, -1, -5],
      pos2D: { x: 0.15, y: 0.35 },
      whatIsIt: "AND, OR, and NOT Boolean logic operations.",
      whyMatters: "The atomic units of computation. All software logic, mathematical addition, and memory addressing are built by combining these simple gates.",
      howItWorks: {
        beginner: "Tiny gates that allow or block electricity based on inputs. By combining them, we build circuits that can add or compare numbers.",
        intermediate: "Uses transistors as electrical switches. For example, two transistors in series make an AND gate; in parallel, they make an OR gate.",
        expert: "CMOS logic gates designed with complementary PMOS and NMOS transistor pairs, operating with picosecond propagation delays and minimal static power leakage.",
      },
      realUse: "Arithmetic Logic Units (ALUs), decoders, registers.",
      difficultyLevel: "Beginner",
      skillsUnlocked: ["Boolean Algebra", "Digital Circuit Design"],
      connectedRealms: ["the-foundations"],
      connectedProjects: [],
      nexusComment: "Electricity goes in, logic comes out. No matter how complex a system is, this is all it does under the hood.",
    },
    {
      id: "bus-highways",
      name: "System Bus Highways",
      type: "bus",
      position: [0, -3, 0],
      pos2D: { x: 0.45, y: 0.7 },
      whatIsIt: "High-speed connection paths between motherboard components.",
      whyMatters: "The communication channel between the CPU, RAM, and storage. Bandwidth determines system throughput.",
      howItWorks: {
        beginner: "A multi-lane highway for data packets. The wider the highway, the more data can travel at once.",
        intermediate: "Parallel trace pathways synchronized by a system clock, transmitting address, control, and data bits simultaneously.",
        expert: "High-speed serial point-to-point buses like PCIe 5.0, using differential signaling and multi-lane configurations (up to x16) to reach 128 GB/s bi-directional bandwidth.",
      },
      realUse: "PCI Express Lanes, Ultra Path Interconnect (UPI).",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Bus Bandwidth Optimization", "Hardware Interfaces"],
      connectedRealms: ["network-pathways"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "Think of this as the nervous system. Without it, the processor and memory are isolated islands.",
    },
  ],
  steps: [
    {
      id: "electricity",
      label: "ELECTRICITY",
      caption: "A voltage difference races through copper traces — the only raw material a computer ever has.",
      nexusLine: "Every line of code eventually becomes electricity moving through places like this.",
      activeLandmarkId: "bus-highways",
    },
    {
      id: "logic",
      label: "LOGIC GATES",
      caption: "Two inputs meet a gate. AND, OR, and NOT are the only primitives — everything else is built from these three.",
      nexusLine: "AND, OR, NOT. Every complex algorithm is built on these three switches.",
      activeLandmarkId: "logic-factory",
    },
    {
      id: "cpu",
      label: "CPU CYCLE",
      caption: "FETCH pulls an instruction from memory. DECODE figures out what it means. EXECUTE makes the ALU act on it.",
      nexusLine: "The CPU fetches the command and decodes it. A tiny clock pulse orchestrates the dance.",
      activeLandmarkId: "cpu-tower",
    },
    {
      id: "memory",
      label: "MEMORY",
      caption: "The CPU sends an address down the bus. RAM answers with the data that lived there.",
      nexusLine: "These structures hold the thoughts before they become action.",
      activeLandmarkId: "ram-city",
    },
    {
      id: "result",
      label: "RESULT",
      caption: "The five stages collapse into one outcome — a bit, a byte, a decision the rest of the program can use.",
      nexusLine: "The calculation is complete, and the cycle begins anew.",
      activeLandmarkId: "cpu-tower",
    },
  ],
};

const NETWORK_PATHWAYS_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "network-pathways",
  title: "Data Packet Journey",
  welcomeSpeech: "Welcome to the nervous system. Let's watch how data connects the world.",
  cameraOverview: {
    position: [12, 10, 15],
    lookAt: [0, 1, -2],
  },
  landmarks: [
    {
      id: "client-terminal",
      name: "Client Terminal",
      type: "node",
      position: [-8, -1, 4],
      pos2D: { x: 0.15, y: 0.7 },
      whatIsIt: "The starting point. Simulates request creation and protocol encapsulation.",
      whyMatters: "Computers become powerful when they connect. All network journeys begin with a client packaging application data.",
      howItWorks: {
        beginner: "A user typing a message. The terminal wraps it in layered digital envelopes so routers know how to deliver it.",
        intermediate: "Prepares raw application payload and pushes it down the OS networking stack (Application -> Transport -> Network -> Physical).",
        expert: "Generates an HTTP POST request payload, tokenizes it into buffers, and passes it to the socket API to prepare TCP segments.",
      },
      realUse: "Web browser request APIs, curl terminal utilities.",
      difficultyLevel: "Beginner",
      skillsUnlocked: ["HTTP Request Formatting", "Socket Programming"],
      connectedRealms: ["code-helix", "the-kernel"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "Your message is no longer text. It has become a packet ready to cross the network.",
    },
    {
      id: "dns-beacon",
      name: "DNS Beacon Tower",
      type: "core",
      position: [-4, 1.5, -4],
      pos2D: { x: 0.35, y: 0.3 },
      whatIsIt: "Domain Name System resolver radar.",
      whyMatters: "Translates human-readable names like example.com into machine-readable IP coordinates.",
      howItWorks: {
        beginner: "The phonebook of the internet. Without it, you'd have to memorize long IP numbers for every website.",
        intermediate: "Performs recursive queries (Root -> TLD -> Authoritative Name Server) to resolve a domain name to an A/AAAA record.",
        expert: "Queries DNS resolvers over UDP port 53. Utilizes EDNS0 extensions and DNSSEC signatures to guarantee record integrity.",
      },
      realUse: "Google Public DNS (8.8.8.8), Cloudflare DNS (1.1.1.1).",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["DNS Record Configuration", "Domain Routing"],
      connectedRealms: ["the-foundations"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "DNS gives us coordinates. Now we know where to travel.",
    },
    {
      id: "router-network",
      name: "Router Network Hub",
      type: "gateway",
      position: [0, 0, 0],
      pos2D: { x: 0.5, y: 0.5 },
      whatIsIt: "Layer 3 gateway choosing packet highways.",
      whyMatters: "Directs packets dynamically across network nodes. Prevents bottleneck congestion and routes around failed lines.",
      howItWorks: {
        beginner: "A mail carrier sorting letters. The router doesn't know the whole map, just which highway leads closest to the final address.",
        intermediate: "Inspects target IP addresses in packet headers and checks local routing tables (updated via BGP or OSPF) to decide the next hop.",
        expert: "Performs prefix-matching on IP address headers at line-rate. Decides egress interfaces utilizing hardware ASIC forwarding tables.",
      },
      realUse: "BGP gateways, core internet transit routers.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["IP Routing Protocols", "Subnet Configuration"],
      connectedRealms: ["the-citadel", "cloud-expanse"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "The router does not know the full journey. Only the next step.",
    },
    {
      id: "firewall-gate",
      name: "Firewall Scanner Gate",
      type: "factory",
      position: [4, 0.5, -4],
      pos2D: { x: 0.65, y: 0.3 },
      whatIsIt: "Access control scan barrier.",
      whyMatters: "Protects systems from malicious attacks by blocking traffic that violates security policies.",
      howItWorks: {
        beginner: "A security guard checking identification at the gate. If your packet matches a banned pattern, it is rejected.",
        intermediate: "Performs packet filtering and stateful inspection, matching ports, TCP flags, and connection states against access lists (ACLs).",
        expert: "Conducts Deep Packet Inspection (DPI) at the Application Layer (Layer 7). Matches packet payloads against signature databases of known CVE exploits.",
      },
      realUse: "AWS WAF, pfSense enterprise firewalls.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Network Access Control Lists", "Threat Mitigation"],
      connectedRealms: ["the-citadel"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "A protective checkpoint. The Firewall checks headers against security policies.",
    },
    {
      id: "server-core",
      name: "Server Core Terminal",
      type: "core",
      position: [8, -1, 4],
      pos2D: { x: 0.85, y: 0.7 },
      whatIsIt: "The destination application server receiving request payloads.",
      whyMatters: "Receives packets, reassembles them, parses the HTTP payload, and serves the response.",
      howItWorks: {
        beginner: "The final mailroom. It opens all the envelope layers, puts the pieces back together, and reads the letter.",
        intermediate: "Accepts raw TCP packets, verifies packet order, strips headers, and passes reassembled stream to the HTTP server process.",
        expert: "Handles socket connection buffers, TCP window size adjustments, and processes payloads via server threads (Node.js, Go).",
      },
      realUse: "Nginx web servers, Node.js API backends.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["API Server Optimization", "TCP Reassembly"],
      connectedRealms: ["the-kernel", "cloud-expanse"],
      connectedProjects: [
        { name: "CommentFellows", slug: "commentfellows" },
        { name: "VisiRoD FIRS", slug: "visirod-firs" },
      ],
      nexusComment: "Touchdown. The server reassembles the payload. The connection was successful.",
    },
  ],
  steps: [
    {
      id: "create",
      label: "MESSAGE CREATE",
      caption: "User writes 'HELLO'. The client starts the journey by preparing raw application data.",
      nexusLine: "Your message is no longer text. It has become a packet ready to cross the network.",
      activeLandmarkId: "client-terminal",
    },
    {
      id: "dns-query",
      label: "DNS LOOKUP",
      caption: "Querying DNS Beacon to resolve host example.com to IP 93.184.216.34.",
      nexusLine: "DNS gives us coordinates. Now we know where to travel.",
      activeLandmarkId: "dns-beacon",
    },
    {
      id: "encapsulate",
      label: "TCP ENCAPSULATION",
      caption: "Data is split into segments. TCP adds source/destination ports and sequence numbers.",
      nexusLine: "We wrap the payload in TCP. Securing sequence numbers to prevent data loss.",
      activeLandmarkId: "client-terminal",
    },
    {
      id: "route",
      label: "IP ROUTING",
      caption: "IP adds addressing headers. Routers inspect targets and choose next hops dynamically.",
      nexusLine: "The router does not know the full journey. Only the next step.",
      activeLandmarkId: "router-network",
    },
    {
      id: "firewall",
      label: "FIREWALL SCAN",
      caption: "Firewall barrier checks headers and states, verifying packets are safe to proceed.",
      nexusLine: "A protective checkpoint. The Firewall checks headers against security policies.",
      activeLandmarkId: "firewall-gate",
    },
    {
      id: "reassemble",
      label: "RECONSTRUCTION",
      caption: "Server Core receives segments, reassembles bytes, and outputs: 'HELLO'.",
      nexusLine: "Touchdown. The server reassembles the payload. The connection was successful.",
      activeLandmarkId: "server-core",
    },
  ],
};

const THE_KERNEL_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "the-kernel",
  title: "Process Spawn Cycle",
  welcomeSpeech: "Welcome to the Machine Control Room. Here, we coordinate life behind the silicon.",
  cameraOverview: {
    position: [0, 8, 14],
    lookAt: [0, 0, -4],
  },
  landmarks: [
    {
      id: "scheduler-tower",
      name: "Process Scheduler Tower",
      type: "core",
      position: [0, 1.5, -8],
      pos2D: { x: 0.5, y: 0.3 },
      whatIsIt: "The CPU multitasking core manager.",
      whyMatters: "The OS scheduler determines which threads get to run on CPU cores, allowing thousands of tasks to run concurrently.",
      howItWorks: {
        beginner: "A traffic coordinator giving time-slices. It assigns turns to applications so fast they seem to run at the same time.",
        intermediate: "Uses execution queues (runqueues) and algorithms like Completely Fair Scheduler (CFS) to hand out time quanta and switch context.",
        expert: "Swaps thread execution contexts by preserving CPU registers (SP, PC, GPRs) and loading the next process state, managing CPU cycles in nanoseconds.",
      },
      realUse: "Linux CFS scheduler, Windows NT dispatcher.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["CPU Multitasking", "Context Switching Scheduling"],
      connectedRealms: ["silicon-foundry", "code-helix"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "We hand out time-slices to keep the world running. Multitasking is just sharing time extremely fast.",
    },
    {
      id: "memory-manager",
      name: "Memory Manager Grid",
      type: "node",
      position: [-6, -0.5, -5],
      pos2D: { x: 0.2, y: 0.6 },
      whatIsIt: "Heap, stack, and page table address translator.",
      whyMatters: "Allows memory virtualization and isolation, preventing applications from corrupting each other's storage boundaries.",
      howItWorks: {
        beginner: "A property developer mapping plots. Every app thinks it owns the whole street, but the manager maps it to real physical locations.",
        intermediate: "Translates virtual addresses to physical RAM using page tables, managing memory pools, heap, stack, and garbage collection.",
        expert: "Coordinates with CPU Memory Management Unit (MMU) to perform virtual page translations, swapping pages to swap space when RAM is exhausted.",
      },
      realUse: "Linux MMU manager, C malloc allocation.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Virtual Address Translation", "RAM Allocation"],
      connectedRealms: ["silicon-foundry", "data-archives"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "Memory is partitioned strictly. Cross the boundary without permission, and you get a Segmentation Fault.",
    },
    {
      id: "file-system",
      name: "File System Archive",
      type: "node",
      position: [6, -0.5, -5],
      pos2D: { x: 0.8, y: 0.6 },
      whatIsIt: "The permanent storage metadata filesystem.",
      whyMatters: "Translates raw sectors on disks into files and directories, tracking access logs and security privileges.",
      howItWorks: {
        beginner: "A massive library index cabinet. You ask for a book title, and it points you to the exact aisle and shelf.",
        intermediate: "Uses indexes (Inodes) to store block addresses, owner permissions, timestamps, and directory mapping listings.",
        expert: "Manages file block allocations on SSD sectors, utilizing journaling (transaction logs) to prevent filesystem corruption during power failure.",
      },
      realUse: "ext4, NTFS, APFS filesystems.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Filesystem Journaling", "Inode Structure Design"],
      connectedRealms: ["data-archives"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "A file is just an abstraction. Underneath, it is blocks of sectors mapped across magnetic disks or flash blocks.",
    },
    {
      id: "device-controller",
      name: "Device Controller Hub",
      type: "gateway",
      position: [-3, -1, 1],
      pos2D: { x: 0.35, y: 0.8 },
      whatIsIt: "Hardware driver interrupt interface hub.",
      whyMatters: "Decouples standard application code from custom hardware-specific register interfaces.",
      howItWorks: {
        beginner: "A translator speaking to accessories. When you tap a key, it translates the raw tap into letters the program understands.",
        intermediate: "Handles hardware interrupts (IRQs) sent by keyboard/mouse controllers, routing requests to device drivers inside the kernel.",
        expert: "Executes Interrupt Service Routines (ISRs) on receiving hardware triggers, transferring data via DMA directly to system RAM.",
      },
      realUse: "USB Bus Drivers, PCI Express controller drivers.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Interrupt Handling", "Device Drivers"],
      connectedRealms: ["silicon-foundry"],
      connectedProjects: [],
      nexusComment: "A keyboard tap triggers an interrupt. The CPU halts immediately, handles the tap, and resumes execution.",
    },
    {
      id: "security-ring",
      name: "Kernel Security Rings",
      type: "factory",
      position: [3, -1, 1],
      pos2D: { x: 0.65, y: 0.8 },
      whatIsIt: "Privilege rings isolating User mode from Kernel mode.",
      whyMatters: "Prevents user applications from executing raw hardware instructions that could hijack the system.",
      howItWorks: {
        beginner: "A security lock. Applications run outside in a public yard, while the system core stays inside the locked vault.",
        intermediate: "Enforces processor execution rings. Ring 3 (User) must perform System Calls (syscalls) to transition to Ring 0 (Kernel) for hardware tasks.",
        expert: "Utilizes CPU execution modes (Supervisor state vs User state). Syscalls trigger hardware traps that switch stacks and execute kernel routines.",
      },
      realUse: "x86 Rings 0-3 enforcement.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["Privilege Isolation", "System Calls"],
      connectedRealms: ["the-citadel"],
      connectedProjects: [],
      nexusComment: "User applications are locked in Ring 3. They must request the kernel's permission in Ring 0 to touch the disk or network.",
    },
  ],
  steps: [
    {
      id: "app-open",
      label: "APP OPEN",
      caption: "User triggers application execution. The OS reads program file headers.",
      nexusLine: "A sleeping file is read from the disk archive.",
      activeLandmarkId: "file-system",
    },
    {
      id: "alloc-memory",
      label: "ALLOCATE MEMORY",
      caption: "Memory Manager reserves stack/heap blocks, mapping virtual address pages to RAM.",
      nexusLine: "Memory Manager partitions a sandbox. Virtual pages map to physical slots.",
      activeLandmarkId: "memory-manager",
    },
    {
      id: "schedule-cpu",
      label: "SCHEDULE PROCESS",
      caption: "A Process Control Block is queued. Scheduler allocates a CPU core time-slice.",
      nexusLine: "The Process Scheduler adds the thread to the execution queue.",
      activeLandmarkId: "scheduler-tower",
    },
    {
      id: "access-hardware",
      label: "HARDWARE ACCESS",
      caption: "The process requests I/O. The system triggers driver interrupts through the hub.",
      nexusLine: "Hardware controller triggers driver routines via interrupts.",
      activeLandmarkId: "device-controller",
    },
    {
      id: "run-app",
      label: "APP RUNNING",
      caption: "Process execution completes privilege checks and outputs results.",
      nexusLine: "Multi-tasking loop active. The application is officially alive.",
      activeLandmarkId: "security-ring",
    },
  ],
};

const CODE_HELIX_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "code-helix",
  title: "Compilation & Execution Lifecycle",
  welcomeSpeech: "This is the Code Helix. The place where human logic compiles into physical reality.",
  cameraOverview: {
    position: [0, 8, 12],
    lookAt: [0, 1, -4],
  },
  landmarks: [
    {
      id: "code-forge",
      name: "The Code Forge",
      type: "node",
      position: [-7, -1, 3],
      pos2D: { x: 0.15, y: 0.7 },
      whatIsIt: "Source code editor workspace.",
      whyMatters: "Programming languages let humans declare complex business logic in readable text.",
      howItWorks: {
        beginner: "A notepad for code. You write commands using words that humans can read.",
        intermediate: "A structured text buffer storing characters that obey strict compiler syntax grammar rules.",
        expert: "Source code encoding (UTF-8) mapped to lexical definitions. Translates key events into text arrays.",
      },
      realUse: "VS Code editor buffers, terminal compilers.",
      difficultyLevel: "Beginner",
      skillsUnlocked: ["Programming Syntax", "Code Structuring"],
      connectedRealms: ["the-kernel"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "We write logic for humans, compile it for machines, and execute it for reality.",
    },
    {
      id: "compiler-engine",
      name: "Compiler Spire",
      type: "core",
      position: [-3, 1.5, -4],
      pos2D: { x: 0.35, y: 0.3 },
      whatIsIt: "High-level text to machine code compiler.",
      whyMatters: "Bridges the semantic gap between human symbols and hardware logic instructions.",
      howItWorks: {
        beginner: "A universal translator. It takes programming syntax and translates it to binary instructions.",
        intermediate: "Parses tokens into an Abstract Syntax Tree (AST), optimizes the AST, and generates binary bytecode.",
        expert: "Performs lexical parsing, optimization passes (dead-code elimination, loop unrolling), and generates target assembly instructions.",
      },
      realUse: "GCC, Clang compiler, V8 JIT engine.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["Compiler Theory", "AST Parsing Optimization"],
      connectedRealms: ["silicon-foundry"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "The AST maps the grammar structure. A logical tree of program intent.",
    },
    {
      id: "ds-factory",
      name: "Data Structure Factory",
      type: "factory",
      position: [0, 0, 0],
      pos2D: { x: 0.5, y: 0.5 },
      whatIsIt: "Data organization models in memory.",
      whyMatters: "Determines access and write speeds. The layout of data structures shapes algorithm logic.",
      howItWorks: {
        beginner: "Different containers. An array is a row of contiguous boxes; a tree is a family hierarchy tree.",
        intermediate: "Memory addresses linked by pointers (Linked Lists, Binary Trees) or contiguous slot arrays.",
        expert: "Data layouts optimizing cache line access. Mappings like hash tables with collision resolution.",
      },
      realUse: "JSON parsing, memory indexes, hash maps.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Data Layout Design", "Memory Pointer Operations"],
      connectedRealms: ["data-archives"],
      connectedProjects: [{ name: "Bus Reservation", slug: "bus-reservation" }],
      nexusComment: "Selecting the correct structure determines execution time. Arrays are contiguous; linked nodes are scattered.",
    },
    {
      id: "algo-arena",
      name: "Algorithm Arena",
      type: "node",
      position: [3, 0.5, -4],
      pos2D: { x: 0.65, y: 0.3 },
      whatIsIt: "Logical sorting, searching, and traversal algorithms.",
      whyMatters: "Reduces run-time processing complexity from slow exponential bounds to fast logarithmic times.",
      howItWorks: {
        beginner: "A recipe for solving a problem step-by-step, like sorting cards or finding paths.",
        intermediate: "A structured algorithm loop (QuickSort, Binary Search) with analysis of time and space complexity.",
        expert: "Solves NP-hard problems using dynamic programming, greedy approaches, or heuristic algorithms.",
      },
      realUse: "Database index searches, route optimization engines.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Algorithm Analysis", "Big-O Notation Calculation"],
      connectedRealms: ["the-foundations"],
      connectedProjects: [{ name: "ZakatLink", slug: "zakatlink" }],
      nexusComment: "Complexity is real. Moving from O(N^2) to O(N log N) makes the difference between lockup and instant results.",
    },
    {
      id: "runtime-engine",
      name: "Execution Engine",
      type: "core",
      position: [7, -1, 3],
      pos2D: { x: 0.85, y: 0.7 },
      whatIsIt: "The virtual machine / CPU runtime executor.",
      whyMatters: "Manages system resources, call stacks, and event loops during active execution.",
      howItWorks: {
        beginner: "The engine that keeps the wheels spinning. It reads compiled codes and sends requests to the OS.",
        intermediate: "Manages call stack frames, heap references, garbage collection loops, and thread execution states.",
        expert: "Tracks execution pointers, registers JIT optimizations, handles asynchronous event loops, and interfaces with syscalls.",
      },
      realUse: "Node.js Event Loop, JVM execution core.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["Event Loop Optimization", "Memory Garbage Collection"],
      connectedRealms: ["the-kernel"],
      connectedProjects: [
        { name: "CommentFellows", slug: "commentfellows" },
        { name: "VisiRoD FIRS", slug: "visirod-firs" },
      ],
      nexusComment: "The call stack tracks where we are. Async tasks offload to system threads, keeping the loop running.",
    },
  ],
  steps: [
    {
      id: "write",
      label: "WRITE CODE",
      caption: "Human writes logic text print('HELLO') inside the Code Forge.",
      nexusLine: "Source code written. Syntax structures program logic.",
      activeLandmarkId: "code-forge",
    },
    {
      id: "compile",
      label: "COMPILE ASSEMBLY",
      caption: "The Compiler parses code into tokens and AST, compiling to binary machine instructions.",
      nexusLine: "Compiler optimizes parser rings, translating human logic to machine opcodes.",
      activeLandmarkId: "compiler-engine",
    },
    {
      id: "ds-map",
      label: "DATA LAYOUT",
      caption: "Runtime registers map variables to memory layout arrays and pointer chains.",
      nexusLine: "Variables allocate in structures, optimizing memory layout paths.",
      activeLandmarkId: "ds-factory",
    },
    {
      id: "execute",
      label: "RUN ALGORITHM",
      caption: "The CPU executes sorting/searching instructions. Call stack frames push/pop dynamically.",
      nexusLine: "Algorithm executes. System resources process steps on the loop.",
      activeLandmarkId: "algo-arena",
    },
    {
      id: "output",
      label: "HARDWARE OUTPUT",
      caption: "Runtime issues print syscall. Kernel routes call to Silicon Foundry display controllers.",
      nexusLine: "Syscall fired. Instruction cycle renders output.",
      activeLandmarkId: "runtime-engine",
    },
  ],
};

const DATA_ARCHIVES_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "data-archives",
  title: "Query & Transaction Execution",
  welcomeSpeech: "Welcome to the Data Archives. Let's inspect how the memory of the universe is indexed.",
  cameraOverview: {
    position: [0, 6, 12],
    lookAt: [0, 0, -4],
  },
  landmarks: [
    {
      id: "crystal-vault",
      name: "Database Crystal Vault",
      type: "core",
      position: [0, 1.5, -8],
      pos2D: { x: 0.5, y: 0.3 },
      whatIsIt: "Immutable relational and document data storage cubes.",
      whyMatters: "Provides durable, transaction-safe storage for application information.",
      howItWorks: {
        beginner: "A secure filing cabinet. Every record is stored inside structured folders that survive computer shut downs.",
        intermediate: "Saves records as structured row/column pages on disk blocks, using write-ahead logs for crash recovery.",
        expert: "Manages data pages with B+Tree leaf blocks, enforcing ACID rules (Atomicity, Consistency, Isolation, Durability).",
      },
      realUse: "PostgreSQL storage pages, SSD tables.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["ACID Compliance Enforcement", "Relational Schema Mapping"],
      connectedRealms: ["the-kernel"],
      connectedProjects: [
        { name: "VisiRoD FIRS", slug: "visirod-firs" },
        { name: "CommentFellows", slug: "commentfellows" },
      ],
      nexusComment: "Crystals store raw bytes. Data here must survive power loss and hardware crashes.",
    },
    {
      id: "query-engine",
      name: "SQL Query Engine",
      type: "factory",
      position: [-6, -0.5, -5],
      pos2D: { x: 0.2, y: 0.6 },
      whatIsIt: "SQL optimizer and plan generator.",
      whyMatters: "Compiles declarative query strings into cost-optimized data scanning execution routines.",
      howItWorks: {
        beginner: "A search manager. You ask for what you want, and it figures out the fastest way to get it.",
        intermediate: "Parses SQL queries -> maps logical relations -> evaluates access cost paths -> outputs execution plan.",
        expert: "Runs cost-based query planners (CBO) to analyze index selectivity, choose join operations, and generate query plans.",
      },
      realUse: "Postgres Planner, SQLite query VM.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["SQL Query Tuning", "Execution Plan Analysis"],
      connectedRealms: ["code-helix"],
      connectedProjects: [{ name: "ZakatLink", slug: "zakatlink" }],
      nexusComment: "Optimizer evaluates paths. It chooses between index scans and table scans.",
    },
    {
      id: "index-towers",
      name: "B-Tree Index Towers",
      type: "node",
      position: [6, -0.5, -5],
      pos2D: { x: 0.8, y: 0.6 },
      whatIsIt: "Multi-level pointer search tree structures.",
      whyMatters: "Speeds up data scanning from slow table scans (O(N)) to fast key lookups (O(log N)).",
      howItWorks: {
        beginner: "The index at the back of a textbook. Tells you the exact page, skipping search over all sheets.",
        intermediate: "Builds a balanced tree (B-Tree) structure. Sorting keys at node branches coordinates quick navigation.",
        expert: "Constructs balanced multi-way search trees (B+Tree) where index keys point directly to file block addresses.",
      },
      realUse: "Database Indexes (Primary Keys, B-Tree indexes).",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Database Index Optimization", "B-Tree Data Structures"],
      connectedRealms: ["the-foundations"],
      connectedProjects: [{ name: "Bus Reservation", slug: "bus-reservation" }],
      nexusComment: "Index structures organize search paths. Data without indexing experiences search delays.",
    },
  ],
  steps: [
    {
      id: "query",
      label: "SUBMIT QUERY",
      caption: "Client issues SQL query. Query engine parses syntax structures.",
      nexusLine: "SQL query parsed. Parsing checks syntax and privilege tables.",
      activeLandmarkId: "query-engine",
    },
    {
      id: "index",
      label: "INDEX SCAN",
      caption: "The query planner references index towers, traversing key branches to find coordinates.",
      nexusLine: "Scanning B-Tree indexes. Skipping unindexed ranges instantly.",
      activeLandmarkId: "index-towers",
    },
    {
      id: "fetch",
      label: "FETCH DATA",
      caption: "Data engine loads target block page from Crystal Vault.",
      nexusLine: "Accessing target block. Data page loaded directly.",
      activeLandmarkId: "crystal-vault",
    },
  ],
};

const CYBER_CITADEL_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "the-citadel",
  title: "Defensive Security Loop",
  welcomeSpeech: "Welcome to the Digital Fortress. Trust here is an architectural decision, not a feeling.",
  cameraOverview: {
    position: [0, 8, 12],
    lookAt: [0, 0, -4],
  },
  landmarks: [
    {
      id: "auth-gate",
      name: "Authentication Gate",
      type: "gateway",
      position: [-6, -0.5, -5],
      pos2D: { x: 0.2, y: 0.6 },
      whatIsIt: "Identity verification and OAuth handshake gate.",
      whyMatters: "Guarantees caller authorization, preventing unauthorized endpoints from accessing resources.",
      howItWorks: {
        beginner: "A badge scanner. Checks password keys and permission tokens before opening system doors.",
        intermediate: "Validates cryptographic signatures on JWT tokens, verifies API credentials, and controls access rules.",
        expert: "Processes stateless JWT tokens signed with asymmetric encryption (RS256). Validates claims and expiry headers.",
      },
      realUse: "Auth0 identity providers, Supabase Auth.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["OAuth Token Handshakes", "Identity Access Management"],
      connectedRealms: ["the-kernel"],
      connectedProjects: [
        { name: "CommentFellows", slug: "commentfellows" },
        { name: "VisiRoD FIRS", slug: "visirod-firs" },
      ],
      nexusComment: "Who goes there? We verify signatures before passing tokens to inner systems.",
    },
    {
      id: "encryption-chamber",
      name: "Encryption Chamber",
      type: "core",
      position: [0, 1.5, -8],
      pos2D: { x: 0.5, y: 0.3 },
      whatIsIt: "Asymmetric public-key cryptographic engine.",
      whyMatters: "Secures data privacy, ensuring intercepted payloads are unreadable without private keys.",
      howItWorks: {
        beginner: "A puzzle box lock. Anyone can close it using the public key, but only the owner can open it with the secret key.",
        intermediate: "Uses mathematical algorithms (RSA, ECC) to encrypt transport payloads and signs certificates.",
        expert: "Implements TLS handshakes, exchanging ephemeral symmetric session keys utilizing Diffie-Hellman curves.",
      },
      realUse: "SSL/TLS HTTPS encryption, AES-256 database storage.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["Public Key Cryptography", "TLS Handshakes"],
      connectedRealms: ["network-pathways"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "Cipher text secures data. Intercepted data is meaningless noise without the key.",
    },
    {
      id: "threat-scanner",
      name: "Threat Intrusion Scanner",
      type: "factory",
      position: [6, -0.5, -5],
      pos2D: { x: 0.8, y: 0.6 },
      whatIsIt: "SQL injection and XSS exploit inspector.",
      whyMatters: "Scans payload fields for exploit patterns, stopping injection attacks before they touch backend runtimes.",
      howItWorks: {
        beginner: "A detector scanning baggage. Checks inputs for weapons or suspicious code patterns.",
        intermediate: "Filters inputs matching regex databases of SQL injection (' OR '1'='1) and cross-site scripting tags.",
        expert: "Conducts deep packet inspection (DPI) and heuristic behavioral logging, blocking endpoints on anomaly logs.",
      },
      realUse: "WAF firewalls, input sanitizers.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Input Sanitization", "Vulnerability Auditing"],
      connectedRealms: ["the-kernel"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "Sanitize all inputs. Never trust user input without validation.",
    },
  ],
  steps: [
    {
      id: "scan",
      label: "THREAT SCAN",
      caption: "Request hits Threat Scanner. Payload fields are parsed for exploit injection patterns.",
      nexusLine: "Inbound threat scanning. Exploit signatures evaluated.",
      activeLandmarkId: "threat-scanner",
    },
    {
      id: "auth",
      label: "IDENTITY AUTH",
      caption: "Auth Gate checks client authorization tokens and signs security clearance.",
      nexusLine: "Checking token signatures. Access permissions validated.",
      activeLandmarkId: "auth-gate",
    },
    {
      id: "encrypt",
      label: "CRYPT ENGINE",
      caption: "Private data registers encrypt using AES-256 blocks inside the Crypt Chamber.",
      nexusLine: "Data payload encrypted. Plain text compiles to cipher text blocks.",
      activeLandmarkId: "encryption-chamber",
    },
  ],
};

const NEURAL_NEBULA_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "neural-nebula",
  title: "Inference & Backpropagation Loop",
  welcomeSpeech: "Welcome to the Neural Nebula. Let's observe how weight matrix equations form learned patterns.",
  cameraOverview: {
    position: [0, 8, 12],
    lookAt: [0, 0, -4],
  },
  landmarks: [
    {
      id: "dataset-river",
      name: "Dataset River",
      type: "node",
      position: [-6, -0.5, -5],
      pos2D: { x: 0.2, y: 0.6 },
      whatIsIt: "Shifting dataset feature streams.",
      whyMatters: "Machine learning relies on raw features and label datasets to discover underlying distributions.",
      howItWorks: {
        beginner: "A stream of cards containing text or picture examples used to train the system.",
        intermediate: "Normalized feature tensors and target label matrices processed in minibatch arrays.",
        expert: "Data preprocessing matrices transforming token weights and image tensors for input queues.",
      },
      realUse: "ML training dataset vectors, data rivers.",
      difficultyLevel: "Beginner",
      skillsUnlocked: ["Data Engineering Tensors", "Feature Normalization"],
      connectedRealms: ["data-archives"],
      connectedProjects: [{ name: "Smart Notebook", slug: "smart-notebook" }],
      nexusComment: "Training streams feed inputs. Clean data makes predictions accurate.",
    },
    {
      id: "neural-galaxy",
      name: "Neural Layer Galaxy",
      type: "core",
      position: [0, 1.5, -8],
      pos2D: { x: 0.5, y: 0.3 },
      whatIsIt: "Dense weight matrix layers.",
      whyMatters: "Calculates complex non-linear combinations of inputs to classify patterns.",
      howItWorks: {
        beginner: "A network of calculation nodes. Each node weighs features and hands results to the next row.",
        intermediate: "Layers of neurons multiplying input tensors by weights, adding biases, and applying ReLU activation.",
        expert: "Forward propagation matrix dot products: Y = Activation(W * X + B) across stacked network layers.",
      },
      realUse: "Large Language Models (LLMs), neural layers.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["Weight Matrix Math", "Activation Function Design"],
      connectedRealms: ["silicon-foundry"],
      connectedProjects: [
        { name: "CommentFellows", slug: "commentfellows" },
        { name: "MediTalk", slug: "meditalk" },
      ],
      nexusComment: "Synaptic weights multiply parameters. Non-linear equations model relationships.",
    },
    {
      id: "training-chamber",
      name: "Gradient Training Chamber",
      type: "factory",
      position: [6, -0.5, -5],
      pos2D: { x: 0.8, y: 0.6 },
      whatIsIt: "Error loss optimizer and weight adjuster.",
      whyMatters: "Updates matrix parameters dynamically using error gradients, enabling neural networks to learn.",
      howItWorks: {
        beginner: "A coach pointing out mistakes. Adjusts network knobs to decrease errors next time.",
        intermediate: "Calculates error distance (Loss) and uses backpropagation to adjust weight matrices.",
        expert: "Runs Gradient Descent using chain rule calculus to propagate error gradients backward through weights.",
      },
      realUse: "PyTorch SGD optimizer, Adam optimization loops.",
      difficultyLevel: "Expert",
      skillsUnlocked: ["Backpropagation Calculus", "Optimization Algorithms"],
      connectedRealms: ["the-foundations"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "Optimization updates parameters. The system adjusts weights to minimize loss.",
    },
  ],
  steps: [
    {
      id: "ingest",
      label: "INGEST DATA",
      caption: "Inputs flow from the Dataset River. Features normalize into arrays.",
      nexusLine: "Features loaded to matrices. Initial values map to input rows.",
      activeLandmarkId: "dataset-river",
    },
    {
      id: "forward",
      label: "FORWARD PASS",
      caption: "Data propagates through layers, multiplied by weights and biases.",
      nexusLine: "Forward pass active. Dot products evaluate hidden layer nodes.",
      activeLandmarkId: "neural-galaxy",
    },
    {
      id: "optimize",
      label: "BACKPROPAGATE",
      caption: "Loss is calculated. Error gradients travel backward, updating weights.",
      nexusLine: "Loss evaluated. Gradients adjust weights via chain rule equations.",
      activeLandmarkId: "training-chamber",
    },
  ],
};

const CLOUD_EXPANSE_KNOWLEDGE: RealmKnowledgeDefinition = {
  realmSlug: "cloud-expanse",
  title: "Cloud Request Distribution",
  welcomeSpeech: "Welcome to the Digital Sky. Let's trace how requests scale across server clusters.",
  cameraOverview: {
    position: [0, 8, 12],
    lookAt: [0, 0, -4],
  },
  landmarks: [
    {
      id: "load-balancer",
      name: "Load Balancer Tower",
      type: "gateway",
      position: [0, 1.5, -8],
      pos2D: { x: 0.5, y: 0.3 },
      whatIsIt: "Traffic distributor and routing node.",
      whyMatters: "Prevents bottlenecks by distributing traffic, maintaining cluster health.",
      howItWorks: {
        beginner: "A check-in desk routing tourists to empty lines, preventing long queues.",
        intermediate: "Evaluates server health and routes requests using Round Robin or Least Connections algorithms.",
        expert: "Layer 7 reverse proxy routing requests utilizing health check registers and SSL termination pools.",
      },
      realUse: "AWS Application Load Balancer, Nginx proxies.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Proxy Load Balancing", "Traffic Routing Policies"],
      connectedRealms: ["network-pathways"],
      connectedProjects: [
        { name: "VisiRoD FIRS", slug: "visirod-firs" },
        { name: "CommentFellows", slug: "commentfellows" },
      ],
      nexusComment: "We balance workloads across the sky, avoiding hardware bottlenecks.",
    },
    {
      id: "server-cluster",
      name: "Horizontal Server Cluster",
      type: "node",
      position: [-6, -0.5, -5],
      pos2D: { x: 0.2, y: 0.6 },
      whatIsIt: "Auto-scaling virtual machine server cluster.",
      whyMatters: "Spins up server instances on demand to handle traffic surges dynamically.",
      howItWorks: {
        beginner: "Spawning backup engines. When one engine gets overloaded, the system boots up more engines.",
        intermediate: "Uses autoscaling triggers to scale virtual instances horizontally inside hypervisors.",
        expert: "Monitors CPU usage thresholds to dynamically provision instances on container host grids.",
      },
      realUse: "Kubernetes Pod autoscaling, AWS EC2 groups.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Horizontal Scaling", "Container Orchestration"],
      connectedRealms: ["the-kernel"],
      connectedProjects: [{ name: "CommentFellows", slug: "commentfellows" }],
      nexusComment: "We add virtual nodes as demand rises. Computation scales dynamically.",
    },
    {
      id: "monitoring-center",
      name: "Metric Monitoring Center",
      type: "factory",
      position: [6, -0.5, -5],
      pos2D: { x: 0.8, y: 0.6 },
      whatIsIt: "System telemetry aggregator.",
      whyMatters: "Monitors latency, memory leaks, and HTTP response codes, ensuring high system uptime.",
      howItWorks: {
        beginner: "A dashboard showing speed dials. Warns you if the system is running hot.",
        intermediate: "Tracks system metrics (CPU, memory, request volume) and alerts on anomalies.",
        expert: "Aggregates telemetry records (Prometheus, OpenTelemetry) to calculate system health metrics.",
      },
      realUse: "Prometheus monitoring, Datadog tracking.",
      difficultyLevel: "Intermediate",
      skillsUnlocked: ["Telemetry Aggregation", "Anomaly Alerting Config"],
      connectedRealms: ["the-citadel"],
      connectedProjects: [{ name: "VisiRoD FIRS", slug: "visirod-firs" }],
      nexusComment: "Telemetry metrics record logs. We trace execution speeds to optimize systems.",
    },
  ],
  steps: [
    {
      id: "incoming",
      label: "INCOMING REQUEST",
      caption: "Traffic hits the Load Balancer, checking healthy targets.",
      nexusLine: "Inbound request parsed. Balancer evaluates cluster capacities.",
      activeLandmarkId: "load-balancer",
    },
    {
      id: "scale",
      label: "AUTO SCALING",
      caption: "High load triggers cluster scale, provisioning new server nodes.",
      nexusLine: "Trigger warning fired. Scaling up new virtual server blocks.",
      activeLandmarkId: "server-cluster",
    },
    {
      id: "metrics",
      label: "LOG TELEMETRY",
      caption: "Monitoring logs CPU usage, request duration, and response headers.",
      nexusLine: "Latency statistics updated. Operational checks green.",
      activeLandmarkId: "monitoring-center",
    },
  ],
};

export const REALM_KNOWLEDGE: Record<string, RealmKnowledgeDefinition> = {
  "silicon-foundry": SILICON_FOUNDRY_KNOWLEDGE,
  "network-pathways": NETWORK_PATHWAYS_KNOWLEDGE,
  "the-kernel": THE_KERNEL_KNOWLEDGE,
  "code-helix": CODE_HELIX_KNOWLEDGE,
  "data-archives": DATA_ARCHIVES_KNOWLEDGE,
  "the-citadel": CYBER_CITADEL_KNOWLEDGE,
  "neural-nebula": NEURAL_NEBULA_KNOWLEDGE,
  "cloud-expanse": CLOUD_EXPANSE_KNOWLEDGE,
};

export function getRealmKnowledge(slug: string): RealmKnowledgeDefinition | null {
  return REALM_KNOWLEDGE[slug] ?? null;
}
